# Site settings 配置站点
title: 'Blog For Jiangfan'
description: 'Life is short，We need Python、MATLAB、Markdown、JavaScript…？'
keyword: 'jiangfan, hezy94, edx, python, openedx, javascript, matlab, mac'
url: 'http://hezy.xin' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2017

# Author 配置博主信息
author: 'Jiangfan'
nickname: 'hezy'
bio: '不务正业的研究生'
avatar: '/assets/img/profile.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments 评论功能
#   default_hidden：是否默认隐藏评论。若是则需要点击一按钮后才显示。 by Ray-Eldath
comments:
  default_hidden: false
  disqus: false
  disqus_url: 'http://35.194.234.238/other/js/embed.dist.js'

  livere: true
  livere_uid: MTAyMC8zNDk0NS8xMTQ4Mg

# Reward 赞赏功能 by Ray-Eldath
reward:
  enable: false
  reward_comment: '动动手指，解救穷人'
  wechatpay: 'http://ray-eldath.image.alimmdn.com/basic/wechatpay.jpg'
  alipay: 'http://ray-eldath.image.alimmdn.com/basic/alipay.jpg'

# b2t 回到顶部 by Ray-Eldath
b2t: true

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'github']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: 'mailto:345818552@qq.com'
  weibo: '//weibo.com/1652598527/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1'
  github: '//github.com/hezy94'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
